import type { Metadata } from "next";

import "./globals.css";
// import '@/styles/scss/app.scss'
import "@/public//fonts/yekan-bakh/fonts.css";
import Navbar from "@/components/Navbar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body >
        <main className="mt-5 flex flex-col px-24 justify-center">
          <Navbar />
          <div className="">{children}</div>
        </main>
      </body>
    </html>
  );
}
